on:
  pull_request:
    paths:
      - .github/workflows/api.*
      - api/**

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  test:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
      - run: |
          package=timekeeper-api
          cargo build --package $package
          cargo run --package $package &
          cargo test --package $package
          kill %1