on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  main-webapp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/trunk-action@v0.5.0
      - run: |
          cd webapp
          rustup target add wasm32-unknown-unknown
          trunk build --release
          aws s3 sync dist/ s3://timekeeper.cruftbusters.com/